lib/geokit/geocoders/mapbox.rb
lib/geokit/multi_geocoder.rb
test/test_multi_geocoder.rb

We're using MapBox with the `MultiGeocoder`, and Geokit's MapBox geocoder did not take the second `options` argument used by multi, resulting in errors like
> Caught an error during Mapbox geocoding call: wrong number of arguments (2 for 1)
This PR fixes that by adding the argument to the appropriate methods, and ignoring it.
The tests simply confirm that no error is raised when geocoding with MapBox.

Make MapBox interface compatible with MultiGeocoder

---

lib/geokit/mappable.rb
test/test_latlng.rb
test/test_mappable.rb

Use Geokit::default_units only if no units supplied.

Raise error when invalid/unsupported units supplied #157

---

lib/geokit/net_adapter/net_http.rb

In some envs creating a Get with url the response is not 200, using uri
it doesn’t happen.

Get.new(url) or Get.new(uri)

---

fixtures/vcr_cassettes/google_city_ordering.yml
lib/geokit/geocoders/google.rb
test/helper.rb
test/test_google_geocoder.rb

When Google results is 2 records with the same accuracy, we should
be able to order the result using the `result['types']` as a last
step.

Better ordering for approximate results

---

Gemfile
README.markdown
fixtures/vcr_cassettes/geobytes_geocode.yml
lib/geokit/geocoders/geobytes.rb
test/test_geobytes_geocoder.rb

This uses the default configuration for Geobyte's Get City Details API. The free service supports up to 50,000 daily queries. Additional query options are also available: http://www.geobytes.com/free-ajax-cities-jsonp-api/#GetCityDetails.

Added support for the Geobytes geocoder

---

lib/geokit/geocoders/google.rb
test/test_google_geocoder.rb

We override the result's accuracy if Google returns an address type of "postal_code". When we do so, we set the precision to "postal_code", but we return "zip+4" for the same accuracy level in other cases (without the override check).
This change returns "zip+4" for precision when accuracy is 6, in all cases.

BUGFIX use consistent precision names

---

lib/geokit/geocoders.rb
lib/geokit/geocoders/google.rb
test/test_google_geocoder.rb

- Add a new Geokit::Geocoders::AccessDeniedError
- Raise this error when Google returns REQUEST_DENIED status
- Include message from response when raising exceptions

Improve handling of Google error responses

---

fixtures/vcr_cassettes/mapbox_forward_geocode.yml
fixtures/vcr_cassettes/mapbox_forward_geocode_city_only.yml
fixtures/vcr_cassettes/mapbox_reverse_geocode.yml
lib/geokit/geocoders/mapbox.rb
test/test_mapbox_geocoder.rb

Fixes #173 
Note that mapbox has removed any notion of `country_code` from their responses :(

Update Mapbox cassettes to support city-only geocoding queries

---

fixtures/vcr_cassettes/google_full_v3_20.yml
lib/geokit/geo_loc.rb
lib/geokit/geocoders/google.rb
test/helper.rb
test/test_geoloc.rb
test/test_google_geocoder.rb

This is not a best way to support provider-specific data but I'm not sure whether it is in geokit philosophy to provide for this kind of variation in the first place. Although there is some google-specific support already, so why not bring more? 
As a cleaner approach I'd suggest creating a container attribute in GeoLoc, named e.g. `custom` and keep there a hash/structured object with provider-specific data. This way top level GeoLoc structure would be more consistent while permitting more flexibility in returned data contents.

adds support for google-specific place_id and formatted_address

---

.travis.yml
lib/geokit/geocoders.rb

After upgrade to Ruby 2.3.0 I was getting `warning: constant Geokit::Geocoders::Geocoder::TimeoutError is deprecated`.
This should be safe to merge. I checked and `Timeout::Error` is supported all the way down to 1.8.7 :)
Cheers
Vlado

Timeout error deprecated

---

geokit.gemspec
test/helper.rb
test/vcr_loader.rb

Webmock 2.0 is not out-of-the box compatible with VCR (https://github.com/vcr/vcr/pull/573)

Old webmock

---

lib/geokit/geocoders/mapbox.rb
test/test_mapbox_geocoder.rb

In this case, like when geocoding City only values, the Mapbox response has the State value at the higher level.

Update Mapbox geocoder to handle geocoding State only values

---

README.markdown

Fixes a README example, where it says about Spain, but suddenly changes the country to Italy :P

Fixes README example

---

lib/geokit/geocoders/bing.rb
lib/geokit/geocoders/ca_geocoder.rb
lib/geokit/geocoders/free_geo_ip.rb
lib/geokit/geocoders/geo_plugin.rb
lib/geokit/geocoders/geobytes.rb
lib/geokit/geocoders/geocodio.rb
lib/geokit/geocoders/geonames.rb
lib/geokit/geocoders/ip.rb
lib/geokit/geocoders/mapquest.rb
lib/geokit/geocoders/maxmind.rb
lib/geokit/geocoders/ripe.rb
lib/geokit/geocoders/us_geocoder.rb
lib/geokit/geocoders/yahoo.rb
lib/geokit/geocoders/yandex.rb

When using ```MultiGeocoder.do_geocode``` it will call ```.do_geocode(address, *args)``` on different geocoders.
However most geocoders implement ```do_geocode(address)``` and not ```do_geocode(address, args)```.
As a result you will see "wrong number of arguments (2 for 1)" errors in your logs.
This PR should fix that issue.

Make sure all geocoders have same do_geocode method signature

---

lib/geokit/geocoders/google.rb

In order to support `result_type` and `location_type` [optional parameters](https://developers.google.com/maps/documentation/geocoding/intro#ReverseGeocoding) we've modified the `do_reverse_geocode` class method. This change allows to get results by granularity. 
For example, you can request just neighborhood results. If you are interested in this PR we can add some tests, but we'll need a Google API key.

Google optional reverse parameters

---

README.markdown

I generated the list with this code, so it should be accurate:
irb(main):002:0> Geokit::Geocoders.constants.map { |sym| Geokit::Geocoders.const_get sym }.select { |klass| klass.superclass == Geokit::Geocoders::Geocoder }.reject { |klass| klass == Geokit::Geocoders::BaseIpGeocoder }.map { |klass| Geokit::Inflector.underscore(klass.provider_name).to_sym }.map(&:inspect).uniq.sort.reject { |s| s == ":multi" }.join(", ")
=> ":bing, :ca, :fcc, :geocodio, :geonames, :google, :map_quest, :mapbox, :maxmind, :opencage, :osm, :us, :yahoo, :yandex"
irb(main):003:0> Geokit::Geocoders.constants.map { |sym| Geokit::Geocoders.const_get sym }.select { |klass| klass.superclass == Geokit::Geocoders::BaseIpGeocoder }.map { |klass| Geokit::Inflector.underscore(klass.provider_name).to_sym …

Update "valid symbols are..." in README for provider_order

---

.rubocop.yml
README.markdown
fixtures/vcr_cassettes/ip_api_geocode.yml
lib/geokit/geocoders.rb
lib/geokit/geocoders/ip_api_geocoder.rb
test/test_ip_api_geocoder.rb

I wanted to play around in this gem and made this. I'm not sure if you guys are interested but I figured I'll throw it up.
I tested basic equality between freegeoip & ip-api:
irb(main):015:0> Geokit::Geocoders::IpApiGeocoder.geocode('13.107.21.200')
=> #<Geokit::GeoLoc:0x00000001e406c8 @all=[#<Geokit::GeoLoc:0x00000001e406c8 ...>], @street_address=nil, @sub_premise=nil, @street_number=nil, @street_name=nil, @city="Redmond", @state="WA", @state_code=nil, @state_name="Washington", @zip="98052", @country_code="US", @success=true, @precision="unknown", @full_address=nil, @lat=47.6801, @lng=-122.1206, @provider="ip_api">
irb(main):016:0> Geokit::Geocoders::FreeGeoIpGeocoder.geocode('13.107.21.200')
=> #<Geokit::GeoLoc:0x00000001b40a68 @all=[#<Geokit::GeoLoc:0x00000001b40a68 ...>], …

Initial implementation for IP-API.com geocoder

---

lib/geokit/geocoders/ipstack.rb

Since the IP geocoding precision is not really accurate, I suggest changing the existing condition (my bad 😅) to set the success condition based on the country code resolution. In our use case, we just care about the country code and now is triggering the fallback unexpectedly when the result doesn't contain the city name.

Modify IPStack success to check the country code

---

fixtures/vcr_cassettes/fcc_reverse_geocode.yml
lib/geokit/geocoders/fcc.rb
test/test_fcc_geocoder.rb

The FCC geocoding API has changed. The old URL is not working. This PR updates to the new URL. Here are the new API docs:
https://geo.fcc.gov/api/census/#!/block/get_block_find

Update URL for FCC Geocoding

---

geokit.gemspec

It removes the deprecation warning while installing this gem.
```bash
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2018-12-01.
Gem::Specification#has_rdoc= called from /bundle/bundler/gems/geokit-758aaeac0d88/geokit.gemspec:16.
```
See https://blog.rubygems.org/2011/03/28/1.7.0-released.html for the deprecation notice.

Remove `has_rdoc` to clean the deprecation warning

---

.hound.yml

As @rafaelpetry said [here](https://github.com/geokit/geokit/pull/229#issuecomment-479695370), it looks like the Hound-Rubocop integration is not properly configured, so we are getting [unexpected offenses](https://github.com/geokit/geokit/pull/229#issuecomment-448144258). Still not sure if it will work, but at least now we're following their [docs](http://help.houndci.com/en/articles/2137566-rubocop) example.

Fix Hound-Rubocop integration to use own custom file

---

lib/geokit/geocoders/opencage.rb
test/test_opencage_geocoder.rb

This PR pretends to fill the **neighborhood** loc in **OpenCage** with the `suburb` component type.

Add neighborhood support for OpenCage

---

lib/geokit/geo_loc.rb
lib/geokit/geocoders/fcc.rb
lib/geokit/geocoders/google.rb
lib/geokit/geocoders/opencage.rb
lib/geokit/geocoders/openstreetmap.rb
test/test_fcc_geocoder.rb
test/test_geo_loc.rb
test/test_google_geocoder.rb
test/test_opencage_geocoder.rb
test/test_openstreetmap_geocoder.rb

It adds a new `geoloc` attribute called **county**. This geographical region is used in a lot of countries as you can see [here](https://en.wikipedia.org/wiki/County).

Add `county` as a new geoloc attribute

---

README.markdown

This PR changes the build badges to SVG for sharper readability ✨
PS: Also removes a `gemnasium` badge, since that service has ben disontinued.

README: Use SVG badges

---

fixtures/vcr_cassettes/opencage_reverse_cerdanyola.yml
lib/geokit/geocoders/opencage.rb
test/test_opencage_geocoder.rb

We aim to maximize the number of results with the city present using OpenCage. To do that, we are adding here `town` as the preferred fallback to populate the city when the specific field is not in the response.

Add town as preferred city fallback for OpenCage

---

lib/geokit/geocoders/yandex.rb

According to the [Yandex Geocoder documentation](https://yandex.ru/dev/maps/geocoder/doc/desc/concepts/input_params.html), the parameter must be called `apikey`.

Fix `key` query parameter for Yandex geocoder

---

.github/workflows/ci.yml

Add more Ruby versions to test matrix to test against. Do not define patch version to always test against newest one by github action.
Ruby 2.5 and 2.6 are no longer update, but in my opinion a lot of projects still uses them.

Replace old Ruby versions with newer ones in test matrix

---

CHANGELOG.md
fixtures/vcr_cassettes/bing_full.yml
fixtures/vcr_cassettes/bing_full_au.yml
fixtures/vcr_cassettes/bing_full_de.yml
geokit.gemspec
lib/geokit/geocoders.rb
lib/geokit/geocoders/bing.rb
lib/geokit/geocoders/yahoo.rb
lib/geokit/multi_geocoder.rb
lib/geokit/version.rb
test/coverage_loader.rb
test/helper.rb
test/test_bing_geocoder.rb
test/test_multi_geocoder.rb
test/test_multi_ip_geocoder.rb
test/test_opencage_geocoder.rb
test/test_yandex_geocoder.rb

* Introduced NoSuchGeocoderError. If you try call a geocoder like :bogus that doesn't exist, an error will be returned.
* Upgraded to coveralls_reborn
* Replaced deprecated URI.escape with CGI.escape
* Fixed old mocha incompatability, now calls mocha/test_unit and not mocha/setup
* Bumped minimum Ruby version
All tests run with **rake test** now pass, including geocoding VCR assertions.

Fixes 2023 - 

---

Rakefile

Running this:
```
eric@tux ~/D/geokit (master $)> bundle exec rake console
irb -rubygems -I lib -r geokit
```
Produces this warning:
```
/home/eric/.rubies/ruby-3.1.2/lib/ruby/3.1.0/irb/init.rb:397: warning: LoadError: cannot load such file -- ubygems
Did you mean?  rubygems
irb(main):001:0>
```
The `ubygems.rb` file has been deprecated since Ruby 2.5. Because requiring RubyGems explicitly has been unnecessary since Ruby 1.9, this pull request removes that require.

Remove require of deprecated ubygems.rb file

---

.gitignore
README.markdown
fixtures/vcr_cassettes/ip_api_pro_geocode.yml
lib/geokit/geocoders/ip_api_geocoder.rb
test/test_ip_api_geocoder.rb

This adds support for ip-api.com pro. See the below screenshot from their "members" documentation.
It's effectively the same endpoint as the free version, except the `pro` subdomain and the `key=...` param. With the paid plan, there are no additional rate limits.

Add support for ip-api.com pro.
